# CHI SQUARE TEST

The chi square tests deals only with categorical variable 

The chi square test is used to test whether there is any association between 2 features and also to test whether the sample data is the estimate of population

# TEST FOR INDEPENDENCE

The test for independence is the chi square test which tells us whether 2 categorical features where independent of each other or not.

In [4]:
import seaborn as sns
import pandas as pd
import numpy as np
import scipy.stats as stats

In [3]:
df=pd.read_csv("D:/Datasets/Placement.csv")

In [4]:
df.head()

sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p  \
0      1      M  67.00   Others  91.00   Others  Commerce     58.00   
1      2      M  79.33  Central  78.33   Others   Science     77.48   
2      3      M  65.00  Central  68.00  Central      Arts     64.00   
3      4      M  56.00  Central  52.00  Central   Science     52.00   
4      5      M  85.80  Central  73.60  Central  Commerce     73.30   

    degree_t workex  etest_p specialisation  mba_p      status    salary  
0   Sci&Tech     No     55.0         Mkt&HR  58.80      Placed  270000.0  
1   Sci&Tech    Yes     86.5        Mkt&Fin  66.28      Placed  200000.0  
2  Comm&Mgmt     No     75.0        Mkt&Fin  57.80      Placed  250000.0  
3   Sci&Tech     No     66.0         Mkt&HR  59.43  Not Placed       NaN  
4  Comm&Mgmt     No     96.8        Mkt&Fin  55.50      Placed  425000.0

In [5]:
df.isnull().sum()

sl_no              0
gender             0
ssc_p              0
ssc_b              0
hsc_p              0
hsc_b              0
hsc_s              0
degree_p           0
degree_t           0
workex             0
etest_p            0
specialisation     0
mba_p              0
status             0
salary            67
dtype: int64

## Now we can test for independence between gender and hsc_s (course purused in higher secondary)

## We are now checking whether both the features are independent about each other or not using chi square test ( test for independence)

## H0 : gender and hsc_s are independent

## H1 : gender and hsc_s are  not independent

As per the concept lets first make the contingency table for observed dat

In [29]:
obs_table=pd.crosstab(df['gender'],df['hsc_s'])
print("Observed frequencies")
print(obs_table)

Observed frequencies
hsc_s   Arts  Commerce  Science
gender                         
F          6        40       30
M          5        73       61


In [9]:
obs=obs_table.values
print(obs)

[[ 6 40 30]
 [ 5 73 61]]


In [12]:
exp_t=stats.chi2_contingency(obs_table)
print(exp_t)

(1.9997559814872248, 0.3679243286067856, 2, array([[ 3.88837209, 39.94418605, 32.16744186],
       [ 7.11162791, 73.05581395, 58.83255814]]))


In [28]:
dof=exp_t[2]
exp=exp_t[3]
print("Expected frequencies")
print(exp)

Expected frequencies
[[ 3.88837209 39.94418605 32.16744186]
 [ 7.11162791 73.05581395 58.83255814]]


In [30]:
chi_squared_stat = (((obs-exp)**2)/exp).sum().sum()
print("chi square statistic")
print(chi_squared_stat)

chi square statistic
1.9997559814872248


In [31]:
crit=stats.chi2.ppf(q = 0.95,df = dof) 
print("critical value for respective confidence interval and degree of freedom")
print(crit)

critical value for respective confidence interval and degree of freedom
5.991464547107979


In [26]:
p_value = 1 - stats.chi2.cdf(x=chi_squared_stat,  
                             df=dof)
print("P value")
print(p_value)

P value
0.3679243286067856


In [27]:
if p_value < 0.05:   
    print(" we are rejecting null hypothesis")
else:
    print("we are accepting null hypothesis")

we are accepting null hypothesis


## Thus gender and hsc_s were independent 

## H0 : work experience and placement status are independent

## H1 : work experience and placement status are not independent

## This test will be carried out with 5% level of significance

In [32]:
obs_table1=pd.crosstab(df['workex'],df['status'])
print("Observed frequencies")
print(obs_table1)

Observed frequencies
status  Not Placed  Placed
workex                    
No              57      84
Yes             10      64


In [33]:
obs1=obs_table1.values
print(obs1)

[[57 84]
 [10 64]]


In [34]:
exp_t1=stats.chi2_contingency(obs_table1)
print(exp_t1)

(15.154425347637423, 9.906584720516494e-05, 1, array([[43.93953488, 97.06046512],
       [23.06046512, 50.93953488]]))


In [35]:
dof1=exp_t1[2]
exp1=exp_t1[3]
print("Expected frequencies")
print(exp1)

Expected frequencies
[[43.93953488 97.06046512]
 [23.06046512 50.93953488]]


In [36]:
chi_squared_stat1 = (((obs1-exp1)**2)/exp1).sum().sum()
print("chi square statistic")
print(chi_squared_stat1)

chi square statistic
16.384957391368694


In [37]:
crit1=stats.chi2.ppf(q = 0.95,df = dof1) 
print("critical value for respective confidence interval and degree of freedom")
print(crit1)

critical value for respective confidence interval and degree of freedom
3.841458820694124


In [40]:
p_value = 1 - stats.chi2.cdf(x=chi_squared_stat1,  
                             df=dof1)
print("P value")
print(p_value)

P value
5.169385992243036e-05


In [41]:
if p_value < 0.05:   
    print(" we are rejecting null hypothesis")
else:
    print("we are accepting null hypothesis")

 we are rejecting null hypothesis


## Therefore we have enough evidence to reject null hypothesis

## Work experience and placement status depends on each other

# GOODNESS OF FIT

It tests whether the distribution of sample categorical data matches an expected distribution

In [5]:
national = pd.DataFrame(["white"]*100000 + ["hispanic"]*60000 +\
                        ["black"]*50000 + ["asian"]*15000 + ["other"]*35000)   #Population

In [6]:
minnesota = pd.DataFrame(["white"]*600 + ["hispanic"]*300 + \
                         ["black"]*250 +["asian"]*75 + ["other"]*150)          #Sample drwan from the above population

## H0 : sample data is estimate of population data

## H1 : sample data is not the estimate of population data

## This test will be carried out with 5% level of significance

In [7]:
national_table = pd.crosstab(index=national[0], columns="count")
minnesota_table = pd.crosstab(index=minnesota[0], columns="count")

print( "National")
print(national_table)
print(" ")
print( "Minnesota")
print(minnesota_table)

National
col_0      count
0               
asian      15000
black      50000
hispanic   60000
other      35000
white     100000
 
Minnesota
col_0     count
0              
asian        75
black       250
hispanic    300
other       150
white       600


In [12]:
observed = minnesota_table

national_ratios = national_table/len(national)  # Get population ratios

expected = national_ratios * len(minnesota)   # Get expected counts

chi_squared_stat = (((observed-expected)**2)/expected).sum()

print(chi_squared_stat )

col_0
count    18.194805
dtype: float64


In the above cell we are calculating the ratios because....if it is the numerical data then we can go with hypothesis of sample mean is the estimate of population mean.

But in here it is categorical data so we are calculation population ratios.

we are multiplyting the length of sample data because we are expecting that sample data is the estimate of population data

In [14]:
crit = stats.chi2.ppf(q = 0.95, 
                      df = 4)   
print("Critical value")
print(crit)

p_value = 1 - stats.chi2.cdf(x=chi_squared_stat,  # Find the p-value
                             df=4)
print("P value")
print(p_value)

Critical value
9.487729036781154
P value
[0.00113047]


In [15]:
stats.chisquare(f_obs= observed,   # Array of observed counts
                f_exp= expected)   # Array of expected counts

Power_divergenceResult(statistic=array([18.19480519]), pvalue=array([0.00113047]))

In [16]:
if p_value < 0.05:   
    print(" we are rejecting null hypothesis")
else:
    print("we are accepting null hypothesis")

 we are rejecting null hypothesis


## Therefore sample data is not the estimate of population data